
from building import *
import rtconfig

cwd     = GetCurrentDir()
src     = Glob('src/*.c')
CPPPATH = [cwd + '/inc']


group = DefineGroup('USER', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
